### PR TITLE
Taskbar guard

### LINKED ISSUE #1183: Taskbar API not working on Linux
During development I had to change the Taskbar handling. We should investigate if this is only a problem on my machine or this is generic for Linux. See some discussion in #1181.

Tested with PopOS 22.04 with both KDE and the PopOS Gnome fork this seems to fail.

image

### PR DESCRIPTION
**Pull request by deboer-tim**
Avoid calling Taskbar.setIconImage() on platforms that don't support it.

Fixes #1183.

### CODE REVIEW

File: ProblemSet/src/org/icpc/tools/contest/util/problemset/ProblemSetEditor.java [hunk 1]
```diff
@@ -537,11 +537,14 @@ public static void main(String[] args) {
...
-			Taskbar.getTaskbar().setIconImage(image);
-		} catch (Exception e) {
-			// could not set icon
+		if (Taskbar.isTaskbarSupported()) {
+			try {
+				BufferedImage image = ImageIO
+						.read(ProblemSetEditor.class.getResourceAsStream("/images/problemSetIcon.png"));
+				Taskbar.getTaskbar().setIconImage(image);
+			} catch (Exception e) {
+				// could not set icon
```
Comment (vmcj) [inline ProblemSet/src/org/icpc/tools/contest/util/problemset/ProblemSetEditor.java:546]: I assume you want to Trace.

**Review by vmcj — APPROVED** [review]
Nitpick
