### PR TITLE
Fix alternating audio in team display presentation

### LINKED ISSUE #1275: Team display presentation plays same gender audio every time.
It seems the team display presentation always plays the same gender. I found two issues, which might explain this:

* The `.female.` file gets assigned both a `male` and `female` tag.
* The `FileReference` constructor doesn't set tags from JSON, which we might want to do,.

### PR DESCRIPTION
**Pull request by nickygerritsen**
I found two issues:

* The disk contest source didn't compare tags of files during merging, which would result in both files being merged into one
* The file reference constructor from JSON didn't set the tags

After fixing both I can successfully alternate audio genders.

Fixes #1275

### CODE REVIEW

File: ContestModel/src/org/icpc/tools/contest/model/internal/FileReference.java [hunk 1]
```diff
@@ -48,7 +54,7 @@ public void updateTags() {
 
 		List<String> list = new ArrayList<>(KNOWN_TAGS.length);
 		for (String t : KNOWN_TAGS) {
-			if (filename.contains(t))
+			if (filename.matches(".*\\b" + t + "\\b.*"))
```
Comment (deboer-tim) [inline ContestModel/src/org/icpc/tools/contest/model/internal/FileReference.java]: My regex fu is not great, but tags will always be between periods (i.e. `.tag.`), so wouldn't `filename.contains("." + t + ".")` be good enough?
